name: CI

on:
  pull_request:
    branches: [ main, alpha ]
    paths:
    - '**.rb'
    - '**.feature'
    - '.github/**'
    - 'docker'
    - 'Gemfile'
    - '*.gemspec'
  push:
    branches: [ main, alpha ]
    paths-ignore:
    - '**.md'

jobs:
  build:
    name: "\U0001F4E6 Build image"
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build image'
        run: |
          docker build -f docker/Dockerfile -t validate-rb .
          mkdir pkg
          docker save validate-rb:latest | gzip > pkg/validate-rb.tar.gz

      - name: "\U0001F4E4 Upload image"
        uses: actions/upload-artifact@v1
        with:
          name: container
          path: pkg/validate-rb.tar.gz

  specs:
    name: 'Run specs'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "\U0001F4E5 Download image"
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: 'Rspec'
        run: |
          docker load < container/validate-rb.tar.gz
          echo "::group::Running rspec"
          docker run --rm validate-rb:latest rspec --force-color
          echo "::endgroup::"

  features:
    name: 'Run features'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "\U0001F4E5 Download image"
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: 'Cucumber'
        run: |
          docker load < container/validate-rb.tar.gz
          echo "::group::Running cucumber"
          docker run --rm validate-rb:latest cucumber --color
          echo "::endgroup::"

  publish:
    name: "\U0001F4E4 Publish"
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha') }}
    runs-on: ubuntu-latest
    needs: [build, specs, features]

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: 'Release'
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn semantic-release --dry-run
