name: Test

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.rb'
    - '**.feature'
    - '.github/**'
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6

    steps:
    - uses: actions/checkout@v2

    - name: Bundler
      run: |
        gem install bundler -v '2.1.4'
        bundle config set path 'vendor/'
        bundle install

    - name: Rspec
      run: bundle exec rspec

    - name: Cucumber
      run: bundle exec cucumber
