name: Test

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.rb'
    - '**.feature'
    - '.github/**'
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ':inbox_tray: Checkout'
        uses: actions/checkout@v2

      - name: ':package: Build image'
        run: |
          docker build -f docker/Dockerfile -t validate-rb .
          docker save validate-rb:latest | gzip > pkg/validate-rb.tar.gz

      - name: ':outbox_tray: Upload image'
        uses: actions/upload-artifact@v1
        with:
          name: container
          path: pkg/validate-rb.tar.gz

  specs:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ':inbox_tray: Download image'
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: 'Rspec'
        run: |
          docker load < pkg/validate-rb.tar.gz
          docker run --rm -ti validate-rb:latest rspec

  features:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ':inbox_tray: Download image'
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: 'Cucumber'
        run: |
          docker load < pkg/validate-rb.tar.gz
          docker run --rm -ti validate-rb:latest cucumber

  publish:
    runs-on: ubuntu-latest
    needs: [build, specs, features]

    steps:
      - name: ':inbox_tray: Download image'
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: ':outbox_tray: Release'
        run: |
          docker load < pkg/validate-rb.tar.gz
          docker run --rm -ti validate-rb:latest rake relese
