name: Run Tests

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.rb'
    - '**.feature'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - shell: docker run ruby:2.6.6 {0}
      run: |
        bundle install --path vendor/
        bundle exec rspec
        bundle exec cucumber
