name: Run Tests

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.rb'
    - '**.feature'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6

    steps:
    - uses: actions/checkout@v2

    - run: |
        gem install bundler -v '2.1.4'
        bundle install --path vendor/
        bundle exec rspec
        bundle exec cucumber
