name: Workflow

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.rb'
    - '**.feature'
    - '.github/**'
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "\U0001F4E5 Checkout"
        uses: actions/checkout@v2

      - name: "\U0001F4E6 Build image"
        run: |
          docker build -f docker/Dockerfile -t validate-rb .
          mkdir pkg
          docker save validate-rb:latest | gzip > pkg/validate-rb.tar.gz

      - name: "\U0001F4E4 Upload image"
        uses: actions/upload-artifact@v1
        with:
          name: container
          path: pkg/validate-rb.tar.gz

  specs:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "\U0001F4E5 Download image"
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: 'Rspec'
        run: |
          docker load < container/validate-rb.tar.gz
          echo "::group::Running rspec"
          docker run --rm validate-rb:latest rspec --force-color
          echo "::endgroup::"

  features:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "\U0001F4E5 Download image"
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: 'Cucumber'
        run: |
          docker load < container/validate-rb.tar.gz
          echo "::group::Running cucumber"
          docker run --rm validate-rb:latest cucumber --color
          echo "::endgroup::"

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [build, specs, features]

    steps:
      - name: "\U0001F4E5 Download image"
        uses: actions/download-artifact@v1
        with:
          name: container

      - name: "\U0001F4E4 Release"
        run: |
          docker load < container/validate-rb.tar.gz
          echo "::group::Running rake release"
          docker run --rm validate-rb:latest rake relese
          echo "::endgroup::"
